### ISSUE TITLE
Instagram sandbox

### ISSUE THREAD

**Issue by valmassoi** [gulzar1996/auto-like-my-gf-insta-pic#8]
Does this work in sandbox mode? I get user not found error

**Comment by gulzar1996** [comment]
Yes it works in sandbox mode but you have to send an invite to the user.

**Comment by valmassoi** [comment]
For my account or for the account I’m liking?

**Comment by gulzar1996** [comment]
Account you are liking its a one time affair though. In Live you don't have to send invite to the user

**Comment by valmassoi** [comment]
Ok cool. Btw I’ve noticed the env vars and port in the readme are wrong... I’ll get a pr to fix them when I get a chance. Cheers
